highlighter: rouge
encoding: UTF-8
future: false
sass:
  style: compressed
permalink: ./:title
url: https://feeds.thechels.uk
## Header
navigation_header:
  - link: "/dotnet"
    title: "Dotnet"
  - link: "/insurance"
    title: "Insurance"
  - link: "/secops"
    title: "SecOps"
  - link: "https://tools.thechels.uk"
    title: "Tools &#11084;"
## SubMenu
