name: RSS Insurance

on:
    schedule:
        - cron: "*/30 * * * *"
    workflow_dispatch:

permissions:
    issues: write
    contents: read

jobs:
    ActuarialPost:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://www.actuarialpost.co.uk/rss_news/actuarialpost.xml"
                  prefix: "[ActuarialPost]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "ActuarialPost"
    InsuranceBusinessMagazine:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://www.insurancebusinessmag.com/uk/rss/"
                  prefix: "[InsuranceBusinessMagazine]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "InsuranceBusinessMagazine"
    Accenture:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://insuranceblog.accenture.com"
                  prefix: "[Accenture]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "Accenture"
    IFAMagazine:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://ifamagazine.com/category/insurance-and-protection/feed/"
                  prefix: "[IFAMagazine]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "IFAMagazine"
    FintechGlobal:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://fintech.global/category/insurtech/feed/"
                  prefix: "[FintechGlobal]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "FintechGlobal"
    InsuranceTimes:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://www.insurancetimes.co.uk/feed/"
                  prefix: "[InsuranceTimes]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "InsuranceTimes"
    PostOnline:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://www.postonline.co.uk/feeds/rss/"
                  prefix: "[PostOnline]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "PostOnline"
    InsuranceNewsUK:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://www.insurancebusinessmagazine.co.uk/feed/"
                  prefix: "[InsuranceNewsUK]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "InsuranceNewsUK"
    ReinsuranceNews:
        # https://www.reinsurancene.ws/feed/
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://www.reinsurancene.ws/feed/"
                  prefix: "[ReinsuranceNews]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "ReinsuranceNews"
    InsuranceJournal:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://www.insurancejournal.com/rss/"
                  prefix: "[InsuranceJournal]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "InsuranceJournal"

    DigitalInsurance:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://www.dig-in.com/feed.rss"
                  prefix: "[DigitalInsurance]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "DigitalInsurance"
    InsuranceEdge:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://insurance-edge.net/feed/"
                  prefix: "[InsuranceEdge]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "InsuranceEdge"
    FinTechTimes:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://thefintechtimes.com/category/fintech/insurtech/feed/"
                  prefix: "[FinTechTimes]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "FinTechTimes"
    InsurTechInsights:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://insurtechinsights.com/feed/"
                  prefix: "[InsurTechInsights]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "InsurTechInsights"
    FCA:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://www.fca.org.uk/news/rss.xml"
                  prefix: "[FCA]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "FCA"
